
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 35;
  public static final int PARANTHESIS_RIGHT = 55;
  public static final int PARANTHESIS_LEFT = 54;
  public static final int AND_AND = 47;
  public static final int NEW_ARRAY = 20;
  public static final int UMINUS = 37;
  public static final int READ_LINE = 23;
  public static final int BOOL_CONSTANT = 60;
  public static final int NOT_EQUAL = 45;
  public static final int DOUBLE = 4;
  public static final int GREATER = 41;
  public static final int PRIVATE = 28;
  public static final int CONTINUE = 18;
  public static final int INTERFACE = 8;
  public static final int INT = 3;
  public static final int LESS = 39;
  public static final int FOR = 12;
  public static final int MINUS = 33;
  public static final int SEMICOLON = 48;
  public static final int NOT = 38;
  public static final int COMMA = 49;
  public static final int BOOL = 5;
  public static final int CLASS = 7;
  public static final int READ_INTEGER = 22;
  public static final int OR_OR = 46;
  public static final int LESS_EQUAL = 40;
  public static final int PLUS = 32;
  public static final int MULTIPLY = 34;
  public static final int IF = 14;
  public static final int THIS = 9;
  public static final int DOT = 50;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int EQUAL = 43;
  public static final int GREATER_EQUAL = 42;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int NULL = 62;
  public static final int BRACKETS_RIGHT = 53;
  public static final int MOD = 36;
  public static final int BREAK = 17;
  public static final int VOID = 2;
  public static final int BRACKETS_LEFT = 52;
  public static final int DTOI = 24;
  public static final int CURLY_BRACKETS_RIGHT = 57;
  public static final int IMPORT = 31;
  public static final int ELSE = 15;
  public static final int PROTECTED = 29;
  public static final int STRING_CONSTANT = 61;
  public static final int BRACKETS_LEFT_RIGHT = 51;
  public static final int ITOD = 25;
  public static final int ITOB = 27;
  public static final int WHILE = 13;
  public static final int PUBLIC = 30;
  public static final int EXTENDS = 10;
  public static final int BTOI = 26;
  public static final int STRING = 6;
  public static final int INT_CONSTANT = 58;
  public static final int CURLY_BRACKETS_LEFT = 56;
  public static final int DOUBLE_CONSTANT = 59;
  public static final int IMPLEMENTS = 11;
  public static final int EQUAL_EQUAL = 44;
  public static final int PRINT = 21;
  public static final int IDENTIFIER = 63;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INT",
  "DOUBLE",
  "BOOL",
  "STRING",
  "CLASS",
  "INTERFACE",
  "THIS",
  "EXTENDS",
  "IMPLEMENTS",
  "FOR",
  "WHILE",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "NEW",
  "NEW_ARRAY",
  "PRINT",
  "READ_INTEGER",
  "READ_LINE",
  "DTOI",
  "ITOD",
  "BTOI",
  "ITOB",
  "PRIVATE",
  "PROTECTED",
  "PUBLIC",
  "IMPORT",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "MOD",
  "UMINUS",
  "NOT",
  "LESS",
  "LESS_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "EQUAL",
  "EQUAL_EQUAL",
  "NOT_EQUAL",
  "OR_OR",
  "AND_AND",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "BRACKETS_LEFT_RIGHT",
  "BRACKETS_LEFT",
  "BRACKETS_RIGHT",
  "PARANTHESIS_LEFT",
  "PARANTHESIS_RIGHT",
  "CURLY_BRACKETS_LEFT",
  "CURLY_BRACKETS_RIGHT",
  "INT_CONSTANT",
  "DOUBLE_CONSTANT",
  "BOOL_CONSTANT",
  "STRING_CONSTANT",
  "NULL",
  "IDENTIFIER"
  };
}

